[project]
name = "viscm"
dynamic = ["version"]
description = "A colormap tool"
readme = "README.rst"
authors = [
  {name = "Nathaniel J. Smith", email = "njs@pobox.com"},
  {name = "Stefan van der Walt", email = "stefanv@berkeley.edu"},
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
]

requires-python = "~=3.7"
dependencies = [
  "numpy",
  "matplotlib",
  "colorspacious",
  "scipy",
]

[project.urls]
repository = "https://github.com/matplotlib/viscm"
# documentation = "https://viscm.readthedocs.io"

[project.license]
text = "MIT"
files = ["LICENSE"]

[project.scripts]
viscm = "viscm.cli:cli"


[build-system]
requires = ["setuptools", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
zip-safe = false
packages = {find = {}}
package-data = {viscm = ["examples/*"]}


[tool.black]
target-version = ["py37", "py38", "py39", "py310", "py311"]

[tool.isort]
profile = "black"
known_first_party = "viscm"
